
const page = () => {
  return (
    <div className="w-[100%] h-auto">
        <h1 className={`w-70% h-auto text-[50px] font-bold ml-6`}>Title</h1>

        <h2 className="ml-8 text-[40px] font-bold">Data Data</h2>
        <p className="w-[70%] h-auto ml-8 text-justify mt-2 mb-8">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Pariatur beatae placeat suscipit, autem, minima aliquam doloremque reiciendis soluta, dolorem quasi consequuntur dolores culpa magnam deleniti illo assumenda. Sequi minima officiis similique quia iusto eaque minus. Ea quo, cum ducimus, a quidem neque, consectetur dolores id placeat laborum reiciendis quaerat nulla? Non nihil qui quisquam maiores, aspernatur praesentium ut molestias mollitia quasi. Sapiente beatae neque obcaecati totam eligendi, cupiditate perferendis, nesciunt ipsum repellendus hic impedit pariatur magni, dolore saepe iusto fugiat. Voluptatem perferendis molestias sint suscipit mollitia quod quasi. Alias labore doloremque sequi ad, cupiditate exercitationem praesentium. Magnam ipsa repudiandae illo suscipit, eveniet sequi explicabo iste reiciendis. Quidem rerum hic accusamus blanditiis facilis voluptatem molestiae ipsa tempora, reprehenderit temporibus. Eius, libero cum nisi eaque minus iste officiis quasi optio facere labore vel praesentium laboriosam tenetur aspernatur ad eveniet atque perferendis laborum provident tempore ipsam. Atque nostrum voluptatem similique ab natus nam sit, deleniti quas, tempore, quam optio dolores sint quibusdam perferendis asperiores eaque recusandae consectetur voluptas adipisci aspernatur officiis corporis aperiam. Dignissimos distinctio impedit totam nobis veritatis? Quas eligendi aliquam at cumque corrupti, a, quo iure similique accusantium blanditiis ullam illum ea. Asperiores dolorem minus possimus modi nisi, omnis perferendis nobis?</p>
        <h2 className="ml-8 text-[40px] font-bold">Data Data</h2>
        <p className="w-[70%] h-auto ml-8 text-justify mt-2 mb-8">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Pariatur beatae placeat suscipit, autem, minima aliquam doloremque reiciendis soluta, dolorem quasi consequuntur dolores culpa magnam deleniti illo assumenda. Sequi minima officiis similique quia iusto eaque minus. Ea quo, cum ducimus, a quidem neque, consectetur dolores id placeat laborum reiciendis quaerat nulla? Non nihil qui quisquam maiores, aspernatur praesentium ut molestias mollitia quasi. Sapiente beatae neque obcaecati totam eligendi, cupiditate perferendis, nesciunt ipsum repellendus hic impedit pariatur magni, dolore saepe iusto fugiat. Voluptatem perferendis molestias sint suscipit mollitia quod quasi. Alias labore doloremque sequi ad, cupiditate exercitationem praesentium. Magnam ipsa repudiandae illo suscipit, eveniet sequi explicabo iste reiciendis. Quidem rerum hic accusamus blanditiis facilis voluptatem molestiae ipsa tempora, reprehenderit temporibus. Eius, libero cum nisi eaque minus iste officiis quasi optio facere labore vel praesentium laboriosam tenetur aspernatur ad eveniet atque perferendis laborum provident tempore ipsam. Atque nostrum voluptatem similique ab natus nam sit, deleniti quas, tempore, quam optio dolores sint quibusdam perferendis asperiores eaque recusandae consectetur voluptas adipisci aspernatur officiis corporis aperiam. Dignissimos distinctio impedit totam nobis veritatis? Quas eligendi aliquam at cumque corrupti, a, quo iure similique accusantium blanditiis ullam illum ea. Asperiores dolorem minus possimus modi nisi, omnis perferendis nobis?</p>
    </div>
  )
}

export default page